### ISSUE TITLE
NameError: uninitialized constant Pubid

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-core#11]
```ruby
> require "pubid-core"
NameError: uninitialized constant Pubid
from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.8.0/lib/pubid-core.rb:3:in `<top (required)>'
```

blocks this https://github.com/relaton/relaton-bsi/issues/24, this https://github.com/relaton/relaton-nist/issues/63, and this https://github.com/relaton/relaton-jis/issues/2

**Comment by ronaldtse** [comment]
@mico can you please help fix this? Thanks!

**Comment by ronaldtse** [comment]
@mico this issue is urgent and blocking @andrew2net .
