### ISSUE TITLE
Incorrect rendering of part and subpart number order

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-core#18]
After update this gem to v 1.8.6 we have:
```ruby
> id = Pubid::Iso::Identifier.parse("ISO/IEC TR 29110-5-1-3:2017") # the part number is "5-1-3"
#<Pubid::Iso::Identifier::TechnicalReport:0x0000000105ad1190 @publisher="ISO", @number="29110"@11, @copublisher="IEC", @year=2017, @part=["5"@17, "1"@19, "3"@21]>

> id.to_s
"ISO/IEC TR 29110-3-1-5:2017" # the part number bcomes "3-1-5"
```

**Comment by ronaldtse** [comment]
@mico can you please help fix this ASAP? Thanks.

**Comment by mico** [comment]
> @mico can you please help fix this ASAP? Thanks.

@ronaldtse @andrew2net this is already fixed in https://github.com/metanorma/pubid-iso/commit/836ec1b3b1600a1934e9f8c8f0907123327d9055

But the error above could appear when using pubid-core 1.8.6 with previous pubid-iso versions.

**Comment by andrew2net** [comment]
> But the error above could appear when using pubid-core 1.8.6 with previous pubid-iso versions.

@mico In such cases we should increase the minor version to prevent using incompatible dependencies.

**Comment by mico** [comment]
> > But the error above could appear when using pubid-core 1.8.6 with previous pubid-iso versions.
> 
> @mico In such cases we should increase the minor version to prevent using incompatible dependencies.

I know that. I didn't know that it will affect other gems.

**Comment by mico** [comment]
Currently affected gem's:
- pubid-cen
```
 expected: "CEN/CLC/TR 17602-80-12:2021"
      got: "CEN/CLC/TR 17602-12-80:2021"
```
- pubid-jis
```
expected: "JIS C 61000-3-2"
     got: "JIS C 61000-2-3"
```
- pubid-bsi
```
expected: "DD CEN/TS 1992-4-2:2009"
     got: "DD CEN/TS 1992-2-4:2009"
```

**Comment by andrew2net** [comment]
> I know that. I didn't know that it will affect other gems.

@mico please make a test for this case

**Comment by mico** [comment]
> > I know that. I didn't know that it will affect other gems.
> 
> @mico please make a test for this case

@ronaldtse @andrew2net I believe we need to run tests on all pubid-* for every pubid-core pull request. So we will see if there are any breaking changes.

**Comment by ronaldtse** [comment]
@mico I agree. @CAMOBAP could you help consider how we can achieve this? Basically pubid-core is the core gem that all pubid-* gems have to require.

**Comment by CAMOBAP** [comment]
@mico @ronaldtse https://github.com/metanorma/pubid-core/actions/workflows/dependent-tests.yml implemented

**Comment by ronaldtse** [comment]
@CAMOBAP this is perfect, thank you very much!

This flow captures the problems succinctly:
https://github.com/metanorma/pubid-core/actions/runs/5790375089/job/15693339030#step:6:251

<img width="1228" alt="Screenshot 2023-08-09 at 8 15 00 AM" src="https://github.com/metanorma/pubid-core/assets/11865/a64cc825-a217-4f1d-82eb-4eca94b51ae2">

**Comment by ronaldtse** [comment]
@mico the BSI and JIS pubid gems are failing due to this change, can you please help fix them? Thanks.
