### ISSUE TITLE
Name of pubid-core is incorrect and actually misleading

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-core#2]
This gem is intended to share code between the pubid-iso and pubid-iec implementations. It is NOT the core of any other PubID parsers. It should be called "pubid-isoiec" instead. Maybe we should just combine the pubid-iso and pubid-iec gems.

**Comment by mico** [comment]
> This gem is intended to share code between the pubid-iso and pubid-iec implementations. It is NOT the core of any other PubID parsers. It should be called "pubid-isoiec" instead. Maybe we should just combine the pubid-iso and pubid-iec gems.

I'm going to use it everywhere, now it's applied only to pubid-iso and pubid-iec but I plan to apply it to all pubid-* implementation (pubid-nist, pubid-ieee).
It should be easy for pubid-ieee, but could be a challenge for pubid-nist (quite different structure).

**Comment by ronaldtse** [comment]
OK, I was worried that the ISO and IEC pubid formats will be consolidated here and that won't work for organizations like IEEE or NIST.

As long as we are keeping SDO-independent data elements in this gem it's okay.
