### ISSUE TITLE
(URGENT) Dependent tests not being able to run

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-core#26]
Seems like a workflow error? @CAMOBAP can you please help? Thanks!

https://github.com/metanorma/pubid-core/actions/runs/6721070666

<img width="934" alt="image" src="https://github.com/metanorma/pubid-core/assets/11865/3587104f-5211-45ed-9901-948ad9903604">

**Comment by mico** [comment]
@ronaldtse @CAMOBAP we need to remove dependency from gemspec before adding a new one to Gemfile, otherwise it might fail when we update minor `pubid-core` version
