### ISSUE TITLE
Some identifiers renders type that don't need to be in output

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-core#36]
After update with adding type to output (https://github.com/metanorma/pubid-core/commit/8882ea33d38ab4005dd8cdd4250b16cc3ccbbfdd)
Now "IS" type included to output:
```
       expected: "IEC 60050-111/AMD1/FRAG1 ED2"
            got: "IEC is 60050-111/AMD1/FRAG1 ED2"
```

**Comment by ronaldtse** [comment]
Yes "IEC 60050-111/AMD1/FRAG1 ED2" is correct.
